<?php
function testform_menu() {
    $items = array();
    $items['calendar_test'] = array(
        'title' => 'Test Schedule',
        'page callback' => 'test_calendar',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['form_test'] = array(
        'title' => 'Test Form!',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('test_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['form_success_page'] = array(
        'title' => 'Your TV Shows',
        'page callback' => 'form_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['api_form_success_page'] = array(
        'title' => 'Api Results',
        'page callback' => 'api_form_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['api_form_test'] = array(
        'title' => 'Test API',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('api_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['episodes/%'] = array(
        'title' => 'Api Results',
        'page callback' => 'episode_guide',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function test_form() {
  $date = '2008-12-31 00:00:00';
  $form['show_name'] = array(
      '#title' => 'Show Name',
      '#type' => 'textfield',
      '#description' => t('Please Your Show Name.'),
  );

  $format = 'Y-m-d H:i';
 
  $form['show_time'] = array(
     '#type' => 'date_select', // types 'date_text' and 'date_timezone' are also supported. See .inc file.
     '#title' => t('Select a date'),
     '#default_value' => $date, 
     '#date_format' => $format,
     '#date_label_position' => 'within', // See other available attributes and what they do in date_api_elements.inc
     '#date_timezone' => 'America/Chicago', // Optional, if your date has a timezone other than the site timezone.
     '#date_increment' => 15, // Optional, used by the date_select and date_popup elements to increment minutes and seconds.
     '#date_year_range' => '-3:+3', // Optional, used to set the year range (back 3 years and forward 3 years is the default).
     '#description' => t('Please Your Show Time.'),
  );   

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Enter',
  );

  return $form;
}

function api_form() {
  $date = '2008-12-31 00:00:00';
  $form['show_name_search'] = array(
      '#title' => 'Show Name',
      '#type' => 'textfield',
      '#description' => t('What show are you looking for.'),
  ); 

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Enter',
  );

  return $form;
}

function api_form_submit($form, &$form_state) {
    $show_name = $form_state['values']['show_name_search'];
    $_SESSION['api_form_values'] = $show_name;

    $form_state['redirect'] = 'api_form_success_page';
    
}

function test_form_submit($form, &$form_state) {
    $show_name = $form_state['values']['show_name'];
    $show_time = $form_state['values']['show_time'];
    $_SESSION['form_values'] = array($show_name, $show_time);

    db_insert('show_info')
    ->fields(array(
      'show_name' => $form_state['values']['show_name'],
      'show_time' => $form_state['values']['show_time'],       
    ))->execute();
    $form_state['redirect'] = 'form_success_page';
    
}

function api_form_success() {
    $show_name = $_SESSION['api_form_values'];
    $show_name_clean = str_replace(" ", "+", $show_name);
    $response = file_get_contents('http://api.tvmaze.com/search/shows?q=' . $show_name_clean);
    $answer = "<p>" . $show_name . "</p><ul>";
    // 
    $decode = json_decode($response, true);
    foreach ($decode as $episode) {
      $answer .= "<li><a href='/episodes/" . $episode['show']['id'] . "'>" . $episode['show']['name'] . "</a></li>";
    }
    return $answer .= "</ul>";
}

function form_success() {
    $answer = "<ul>";
    $result = db_query('SELECT * FROM show_info');
      foreach ($result as $record) {
        $answer .= "<li>Show Name: " . $record->show_name . " - Show Time: " . $record->show_time . "</li>";
      }
    return $answer .= "</ul>";
}

function episode_guide($arg){
  $response = file_get_contents('http://api.tvmaze.com/shows/' . $arg . '/episodes');
  $show = file_get_contents('http://api.tvmaze.com/shows/' . $arg);
  $answer = "<ul>";
  $decode = json_decode($response, true);
  $show_data = json_decode($show, true);
  $show_name = $show_data['name'];
  
  $dates = array();
  foreach ($decode as $episode) {
    $answer .= "<li>" . $episode['name'] . ": " . $episode['airtime']  . " " . $episode['airdate'] . "</li>";
    $episode_info = array("Show Name"=> $show_name, "Show Id"=>$arg, "Episode Name"=>$episode['name'], "Episode Date"=> $episode['airdate']);
    array_push($dates, $episode_info);
  }
  $_SESSION['calendar_info'] = $dates;
  return $answer .= "</ul>";
}

function test_calendar(){
    $testvar = $_SESSION['calendar_info'];
    drupal_add_js(array('testform' => array('testvar' => $testvar)), array('type' => 'setting'));
    drupal_add_js(drupal_get_path('module', 'testform') . '/js/testform.js');
    return "<div><button class='prev_btn'>Previous Week</button><button class='today_btn'>Today</button><button class='next_btn'>Next Week</button><div class='container calendar_holder'></div></div>";
}